# Generated by Django 4.1.13 on 2024-04-02 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.CharField(max_length=500, verbose_name='URL изображения')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('is_related_price', models.BooleanField(blank=True, default=False, null=True, verbose_name='Цена')),
                ('author_name', models.CharField(max_length=50, verbose_name='Автор')),
                ('author_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('posted_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
        ),
    ]
